server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.herig.redis.entity

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  cache:
    type: redis
  redis:
    host: localhost
    port: 6389
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 10000
    timeout: 0
    lettuce:
      pool:
        max-active: 16
        max-wait: 10ms
    database: 0
